# Generated by Django 4.0.1 on 2022-01-23 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='pnone',
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='SOME STRING', max_length=12),
        ),
    ]
